spring.application.name=CafeManagement
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0&sslmode=require&pgbouncer=true
spring.datasource.username=postgres.sznqftxmgyxuizwogkis
spring.datasource.password=hnUwq4bs8Cv6
spring.datasource.driver-class-name=org.postgresql.Driver


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pnguyencongthanh90@gmail.com
spring.mail.password=vgam bkoh ubxu rmyv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

spring.jpa.properties.hibernate.jdbc.use_streams_for_binary=false
spring.jpa.properties.hibernate.query.in_clause_parameter_padding=false
spring.jpa.properties.jakarta.persistence.query.timeout=30000
server.port=${PORT:10000}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=
spring.datasource.hikari.initialization-fail-timeout=10000